version: '3.8'

services:
  app:
    container_name: griffin-test
    build: .
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - APP_ENV=test
      - PORT=3000
      - DATABASE_URL=file:./data/griffin.db

