version: '3.8'

services:
  app:
    container_name: griffin-dev
    build: .
    restart: always
    ports:
      - "30020:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - APP_ENV=dev
      - PORT=3000
      - DATABASE_URL=file:./data/griffin.db

